# Opciones de la JVM para el demonio de Gradle.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# AndroidX (obligatorio para Jetpack Compose / Material 3).
android.useAndroidX=true

# Kotlin code style oficial.
kotlin.code.style=official

# Genera solo recursos del propio módulo (compilación más rápida).
android.nonTransitiveRClass=true
